name: Build and Deploy

on:
  push:
    branches:
      - main   # Triggers the workflow on push to main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust to your project's Node version

      - name: Install dependencies
        run: npm install       # Adjust if you're using a different package manager

      - name: Run tests
        run: npm test          # Adjust to your testing command, or remove if not needed

      - name: Build project
        run: npm run build     # Adjust to your build command
